### ISSUE TITLE
tpch benchmark docker-compose up not working

### ISSUE THREAD

**Issue by j4ckcyw** [ballista-compute/ballista#495]
I'm running this inside WSL. Looks like the scheduler is not able to start up. See attached exception below. On the other hand, I am able to run the benchmark via cargo, e.g. `cargo run --release --bin scheduler`. Is this a set up problem? Or a bug?

```
ballista-scheduler_1  | thread 'main' panicked at 'not currently running on a Tokio 0.2.x runtime.', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/handle.rs:118:28
ballista-scheduler_1  | stack backtrace:

ballista-scheduler_1  |    0:     0x56111fe5f390 - std::backtrace_rs::backtrace::libunwind::trace::h04d12fdcddff82aa
ballista-scheduler_1  |                                at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:100:5
ballista-scheduler_1  |    1:     0x56111fe5f390 - std::backtrace_rs::backtrace::trace_unsynchronized::h1459b974b6fbe5e1
ballista-scheduler_1  |                                at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
ballista-scheduler_1  |    2:     0x56111fe5f390 - std::sys_common::backtrace::_print_fmt::h9b8396a669123d95
ballista-scheduler_1  |                                at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:67:5
ballista-scheduler_1  |    3:     0x56111fe5f390 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he009dcaaa75eed60
ballista-scheduler_1  |                                at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:46:22
ballista-scheduler_1  |    4:     0x56111fe843fc - core::fmt::write::h77b4746b0dea1dd3
ballista-scheduler_1  |                                at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/fmt/mod.rs:1078:17
ballista-scheduler_1  |    5:     0x56111fe57e42 - std::io::Write::write_fmt::heb7e50902e98831c
etcd_1                | 2021-02-09 15:14:42.403143 W | auth: simple token is not cryptographically signed
ballista-scheduler_1  |                                at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/io/mod.rs:1518:15
ballista-scheduler_1  |    6:     0x56111fe61d45 - std::sys_common::backtrace::_print::h2d880c9e69a21be9
ballista-scheduler_1  |                                at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:49:5
ballista-scheduler_1  |    7:     0x56111fe61d45 - std::sys_common::backtrace::print::h5f02b1bb49f36879
ballista-scheduler_1  |                                at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:36:9
ballista-scheduler_1  |    8:     0x56111fe61d45 - std::panicking::default_hook::{{closure}}::h658e288a7a809b29
ballista-scheduler_1  |                                at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:208:50
ballista-scheduler_1  |    9:     0x56111fe619e8 - std::panicking::default_hook::hb52d73f0da9a4bb8
ballista-scheduler_1  |                                at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:227:9
ballista-scheduler_1  |   10:     0x56111fe624e1 - std::panicking::rust_panic_with_hook::hfe7e1c684e3e6462
ballista-scheduler_1  |                                at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:593:17
ballista-scheduler_1  |   11:     0x56111fe62027 - std::panicking::begin_panic_handler::{{closure}}::h42939e004b32765c
ballista-scheduler_1  |                                at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:499:13
ballista-scheduler_1  |   12:     0x56111fe5f84c - std::sys_common::backtrace::__rust_end_short_backtrace::h9d2070f7bf9fd56c
ballista-scheduler_1  |                                at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:141:18
ballista-scheduler_1  |   13:     0x56111fe61f89 - rust_begin_unwind
ballista-scheduler_1  |                                at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
ballista-scheduler_1  |   14:     0x56111fe818a1 - core::panicking::panic_fmt::ha0bb065d9a260792
ballista-scheduler_1  |                                at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:92:14
ballista-scheduler_1  |   15:     0x56111fe81633 - core::option::expect_failed::h4c033402fb75f2bf
ballista-scheduler_1  |                                at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/option.rs:1260:5
ballista-scheduler_1  |   16:     0x56111f6ed391 - tokio::runtime::handle::Handle::current::he3dea28523ffca9f
ballista-scheduler_1  |   17:     0x56111f698825 - tokio::runtime::blocking::pool::spawn_blocking::h62630e4847be1a7b
ballista-scheduler_1  |   18:     0x56111f6a46dc - <hyper::client::connect::dns::GaiResolver as tower_service::Service<hyper::client::connect::dns::Name>>::call::h7103a7233aaec954
ballista-scheduler_1  |   19:     0x56111f2c06a6 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hbbddd8fc77e06a2c
ballista-scheduler_1  |   20:     0x56111f2cb3eb - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::he57057d8319e490b
ballista-scheduler_1  |   21:     0x56111f2b599c - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h7e2dbd5e1ab07402
ballista-scheduler_1  |   22:     0x56111f16ca0c - <tonic::transport::service::reconnect::Reconnect<M,Target> as tower_service::Service<Request>>::poll_ready::h68701050ad9cf139
ballista-scheduler_1  |   23:     0x56111f18c86f - <tower_util::either::Either<A,B> as tower_service::Service<Request>>::poll_ready::hde7a89a7796a1102
ballista-scheduler_1  |   24:     0x56111f271ca9 - <tower_util::boxed::sync::Boxed<S> as tower_service::Service<Request>>::poll_ready::h8aebcd28cc415789
ballista-scheduler_1  |   25:     0x56111f67965a - <tonic::transport::service::connection::Connection as tower_service::Service<http::request::Request<tonic::body::BoxBody>>>::poll_ready::hc17d7e88713959ef
ballista-scheduler_1  |   26:     0x56111f2c3143 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hc49a3c8302f1df67
ballista-scheduler_1  |   27:     0x56111f28790f - etcd_client::client::Client::connect::{{closure}}::h507733f412407847
ballista-scheduler_1  |   28:     0x56111f2bbc68 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h9bfd4b058eabd732
ballista-scheduler_1  |   29:     0x56111f1612a2 - std::thread::local::LocalKey<T>::with::h51e0e573ae8db607
ballista-scheduler_1  |   30:     0x56111f26ef9a - tokio::runtime::enter::Enter::block_on::he83304971f8221c0
ballista-scheduler_1  |   31:     0x56111f232e9b - tokio::runtime::thread_pool::ThreadPool::block_on::h9c99ec65afdd26e0
ballista-scheduler_1  |   32:     0x56111f1fe57b - tokio::runtime::Runtime::block_on::h898bf8eaea10585b
ballista-scheduler_1  |   33:     0x56111f1e3de0 - scheduler::main::h5217a25f2132f8ca
ballista-scheduler_1  |   34:     0x56111f1b0b63 - std::sys_common::backtrace::__rust_begin_short_backtrace::h8c1a2e9bd9d0a5d6
ballista-scheduler_1  |   35:     0x56111f18f80d - std::rt::lang_start::{{closure}}::hc4093a0280e96738
ballista-scheduler_1  |   36:     0x56111fe62907 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h57e2a071d427b24c
ballista-scheduler_1  |                                at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/ops/function.rs:259:13
ballista-scheduler_1  |   37:     0x56111fe62907 - std::panicking::try::do_call::h81cbbe0c3b30a28e
ballista-scheduler_1  |                                at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:381:40
ballista-scheduler_1  |   38:     0x56111fe62907 - std::panicking::try::hbeeb95b4e1f0a876
ballista-scheduler_1  |                                at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:345:19
ballista-scheduler_1  |   39:     0x56111fe62907 - std::panic::catch_unwind::h59c48ccb40a0bf20
ballista-scheduler_1  |                                at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panic.rs:396:14
ballista-scheduler_1  |   40:     0x56111fe62907 - std::rt::lang_start_internal::ha53ab63f88fee728
ballista-scheduler_1  |                                at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/rt.rs:51:25
ballista-scheduler_1  |   41:     0x56111f1e3ea2 - main
ballista-scheduler_1  |   42:     0x7ffa91f7809b - __libc_start_main
ballista-scheduler_1  |   43:     0x56111f15803a - _start
ballista-scheduler_1  |   44:                0x0 - <unknown>
```

**Comment by andygrove** [comment]
I'm also seeing this
