### ISSUE TITLE
Index out of bounds error when reading a parquet file with many partitions

### ISSUE THREAD

**Issue by christophertrml** [ballista-compute/ballista#559]
I have a parquet file that is broken up into 200 partitions, and a development environment exactly as described in the developer setup docs. I have a simple rust project with dependencies set up exactly like the benchmark project is (which worked for me), so dependencies of:

```
arrow = { git = "https://github.com/apache/arrow", rev="7660a22" }
arrow-flight = { git = "https://github.com/apache/arrow", rev="7660a22" }
datafusion = { git = "https://github.com/apache/arrow", rev="7660a22" }
parquet = { git = "https://github.com/apache/arrow", rev="7660a22" }
```

And then running a query as follows:

```

#[tokio::main]
async fn main() -> Result<()> {
    let mut settings = HashMap::new();
    settings.insert("batch.size".to_owned(), "32768".to_owned());

    let ctx = BallistaContext::remote("localhost", 50050, settings);

    ctx.register_parquet("poi", "/path/to/my/parquet/directory");


    let df = ctx.sql("SELECT city FROM poi")?;
    let mut batches = vec![];
    let mut stream = df.collect().await?;
    while let Some(result) = stream.next().await {
        let batch = result?;
        batches.push(batch);
    }
    pretty::print_batches(&batches)?;
    
    Ok(())
}
```

And the executor logs are panicking with the following logs (many versions of this):

```
[2021-02-17T05:21:53Z INFO  ballista::executor::flight_service] Received do_get request
[2021-02-17T05:21:54Z INFO  ballista::executor::flight_service] ExecutePartition: job=2f2d2a94-7962-4033-aa5e-3789aec3d7f7, stage=1, partition=20
    ProjectionExec { expr: [(Column { name: "city" }, "city")], schema: Schema { fields: [Field { name: "city", data_type: U
      ParquetExec: partitions=8
    
[2021-02-17T05:21:54Z INFO  ballista::executor::flight_service] Writing results to /tmp/.tmp00tbU6/2f2d2a94-7962-4033-aa5e-3789aec3d7f7/1/20/data.arrow
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 8 but the index is 20', /home/chris/.cargo/git/checkouts/arrow-3a9cfebb6b7b2bdc/7660a22/rust/datafusion/src/physical_plan/parquet.rs:784:25
stack backtrace:
   0:     0x55aad15dd1c0 - std::backtrace_rs::backtrace::libunwind::trace::hb4de9797f80b7b8c
                               at /rustc/d1206f950ffb76c76e1b74a19ae33c2b7d949454/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55aad15dd1c0 - std::backtrace_rs::backtrace::trace_unsynchronized::h59566d0bd20efff7
                               at /rustc/d1206f950ffb76c76e1b74a19ae33c2b7d949454/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55aad15dd1c0 - std::sys_common::backtrace::_print_fmt::hcfa5ce6be50275d4
                               at /rustc/d1206f950ffb76c76e1b74a19ae33c2b7d949454/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55aad15dd1c0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd8c307a38b9bab04
                               at /rustc/d1206f950ffb76c76e1b74a19ae33c2b7d949454/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55aad15ffd1c - core::fmt::write::h3868db8542c90941
                               at /rustc/d1206f950ffb76c76e1b74a19ae33c2b7d949454/library/core/src/fmt/mod.rs:1096:17
   5:     0x55aad15d5de2 - std::io::Write::write_fmt::hab90295d5a0f197d
                               at /rustc/d1206f950ffb76c76e1b74a19ae33c2b7d949454/library/std/src/io/mod.rs:1568:15
   6:     0x55aad15df915 - std::sys_common::backtrace::_print::h19224910b8700cf1
                               at /rustc/d1206f950ffb76c76e1b74a19ae33c2b7d949454/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55aad15df915 - std::sys_common::backtrace::print::h25dedfa68c5fb84a
                               at /rustc/d1206f950ffb76c76e1b74a19ae33c2b7d949454/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55aad15df915 - std::panicking::default_hook::{{closure}}::h12c5765653a72a42
                               at /rustc/d1206f950ffb76c76e1b74a19ae33c2b7d949454/library/std/src/panicking.rs:208:50
   9:     0x55aad15df3c3 - std::panicking::default_hook::he65cee71c4209f0c
                               at /rustc/d1206f950ffb76c76e1b74a19ae33c2b7d949454/library/std/src/panicking.rs:225:9
  10:     0x55aad15e00b1 - std::panicking::rust_panic_with_hook::h01a674d863fe0d8a
                               at /rustc/d1206f950ffb76c76e1b74a19ae33c2b7d949454/library/std/src/panicking.rs:591:17
  11:     0x55aad15dfbf7 - std::panicking::begin_panic_handler::{{closure}}::h9b9fecf185178864
                               at /rustc/d1206f950ffb76c76e1b74a19ae33c2b7d949454/library/std/src/panicking.rs:497:13
  12:     0x55aad15dd65c - std::sys_common::backtrace::__rust_end_short_backtrace::h57be46a42dc7f24b
                               at /rustc/d1206f950ffb76c76e1b74a19ae33c2b7d949454/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55aad15dfb59 - rust_begin_unwind
                               at /rustc/d1206f950ffb76c76e1b74a19ae33c2b7d949454/library/std/src/panicking.rs:493:5
  14:     0x55aad15fd431 - core::panicking::panic_fmt::h20225113c4a2f8fd
                               at /rustc/d1206f950ffb76c76e1b74a19ae33c2b7d949454/library/core/src/panicking.rs:92:14
  15:     0x55aad15fd3f2 - core::panicking::panic_bounds_check::h5752306d250b5620
                               at /rustc/d1206f950ffb76c76e1b74a19ae33c2b7d949454/library/core/src/panicking.rs:69:5
  16:     0x55aad0fe9474 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h044736c9442e021b
  17:     0x55aad0fed9c9 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hb682141b4e005ccf
  18:     0x55aad0d811f1 - <ballista::executor::flight_service::BallistaFlightService as arrow_flight::flight_service_server::FlightService>::do_get::__do_get::{{closure}}::h293ce338b6903e5a
  19:     0x55aad0d74945 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hb4273cb8225ebb01
  20:     0x55aad0b83442 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::he918808dbbc04e6b
  21:     0x55aad0b6ebe1 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h83f5c616502e8be4
  22:     0x55aad0ae67ad - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::he3046a4f88647c9e
  23:     0x55aad0ae2ac5 - <tower::util::either::Either<A,B> as core::future::future::Future>::poll::hffc38b41a9fcd401
  24:     0x55aad0ae25e5 - <tower::util::either::Either<A,B> as core::future::future::Future>::poll::hb17486fa857f0c65
  25:     0x55aad0ae5d23 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::h66ea7336d4561577
  26:     0x55aad0bbc179 - <futures_util::future::try_future::MapErr<Fut,F> as core::future::future::Future>::poll::h5385eb96a1a79aef
  27:     0x55aad0c263f3 - <hyper::proto::h2::server::H2Stream<F,B> as core::future::future::Future>::poll::h9439a26333f09b0c
  28:     0x55aad0c53c7e - std::panicking::try::hb3969243e2f394ae
  29:     0x55aad0bcb001 - tokio::runtime::task::harness::poll_future::h9426aed5e18cb959
  30:     0x55aad0bccae2 - tokio::runtime::task::harness::Harness<T,S>::poll::h45726da9dd07241a
  31:     0x55aad1347391 - std::thread::local::LocalKey<T>::with::h70b97dbc7c82aaee
  32:     0x55aad13517f2 - tokio::runtime::thread_pool::worker::Context::run_task::h834d6c003105e404
  33:     0x55aad1350d4a - tokio::runtime::thread_pool::worker::Context::run::h52a80af0eb0d5f04
  34:     0x55aad13448e3 - tokio::macros::scoped_tls::ScopedKey<T>::set::h45248c9bf8957865
  35:     0x55aad1350876 - tokio::runtime::thread_pool::worker::run::ha276f28f5a12d39c
  36:     0x55aad1360d60 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h6980eb0d40beac6a
  37:     0x55aad1340aa5 - std::panicking::try::hd19f859f827cc1f3
  38:     0x55aad135f2bc - tokio::runtime::task::harness::Harness<T,S>::poll::hd8fd412af6eefc3f
  39:     0x55aad1343507 - std::sys_common::backtrace::__rust_begin_short_backtrace::hbfb8ee33d2ab4eea
  40:     0x55aad135461a - core::ops::function::FnOnce::call_once{{vtable.shim}}::hcfb4ba6b94a6e595
  41:     0x55aad15e493a - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h321523073ee11258
                               at /rustc/d1206f950ffb76c76e1b74a19ae33c2b7d949454/library/alloc/src/boxed.rs:1546:9
  42:     0x55aad15e493a - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf0e85e12c83b99b3
                               at /rustc/d1206f950ffb76c76e1b74a19ae33c2b7d949454/library/alloc/src/boxed.rs:1546:9
  43:     0x55aad15e493a - std::sys::unix::thread::Thread::new::thread_start::hba22c7961aa0e2f8
                               at /rustc/d1206f950ffb76c76e1b74a19ae33c2b7d949454/library/std/src/sys/unix/thread.rs:71:17
  44:     0x7f13dc0bf609 - start_thread
  45:     0x7f13dbe91293 - clone
  46:                0x0 - <unknown>
```

**Comment by andygrove** [comment]
I reproduced this by changing one of the benchmark queries to `select l_returnflag from lineitem` and running against a data source with 96 partitions on my 24 core desktop. I am running against a single executor.

The scheduler shows:

```
execute_query_stage() stage_id=1
    ProjectionExec { expr: [(Column { name: "l_returnflag" }, "l_returnflag")], schema: Schema { fields: [Field { name: "l_r
      ParquetExec: partitions=24
```

The executor shows many messages like this:

```
ExecutePartition: job=3a33cbc6-8797-4680-a095-f962811b6c92, stage=1, partition=23
    ProjectionExec { expr: [(Column { name: "l_returnflag" }, "l_returnflag")], schema: Schema { fields: [Field { name: "l_r
      ParquetExec: partitions=8
```

**Comment by andygrove** [comment]
After improving the logging, I see the scheduler has:

```
QueryStageExec: job=e1287b08-a605-494b-acd6-80866e6ccc6b, stage=1
  ProjectionExec { expr: [(Column { name: "l_returnflag" }, "l_returnflag")], schema: Schema { fields: [Field { name: "l_r
    ParquetExec: partitions=24, files=96
```

Executor has:

```
    ProjectionExec { expr: [(Column { name: "l_returnflag" }, "l_returnflag")], schema: Schema { fields: [Field { name: "l_r
      ParquetExec: partitions=8, files=96
```

By default, the DataFusion context will use the number of cores to determine how to divide the parquet files into partitions. We should be explicit when creating DataFusion contexts and specify the concurrency level based on Ballista configs. 

This could likely be a serde issue where we ignore the concurrency levels.
